url: https://122e4e-mapbox.global.ssl.fastly.net
api: https://122e4e-mapbox.global.ssl.fastly.net/core
tileApi: https://api.mapbox.com
accessToken: pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejh2N21nMzAxMmQzMnA5emRyN2lucW0ifQ.jSE-g2vsn48Ry928pqylcg
env: staging
source: docs
permalink: /:categories/:title/
baseurl: /mapbox.js
mapboxjs: v3.1.1
mapboxjsbase: /mapbox.js/dist
defaultid: 'mapbox.streets'
future: true
